# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{disp3D}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Toshiyasu Shimizu"]
  s.date = %q{2011-10-19}
  s.description = %q{disp3D provide 3D GUI framework}
  s.email = %q{toshi0328@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/camera.rb",
    "lib/disp3D.rb",
    "lib/helloworld.rb",
    "lib/manipulator.rb",
    "lib/node.rb",
    "lib/node_collection.rb",
    "lib/node_lines.rb",
    "lib/node_points.rb",
    "lib/node_tea_pod.rb",
    "lib/scene_graph.rb",
    "lib/view.rb",
    "test/helper.rb",
    "test/test_line.rb",
    "test/test_lines.rb",
    "test/test_point.rb",
    "test/test_points.rb",
    "test/test_tea_pod.rb"
  ]
  s.homepage = %q{http://github.com/toshi0328/disp3D}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{disp3D provide 3D GUI framework.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<gmath3D>, [">= 0"])
      s.add_development_dependency(%q<ruby-opengl>, ["= 0.60.1"])
      s.add_development_dependency(%q<qtbindings>, ["= 4.6.3.4"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<gmath3D>, [">= 0"])
      s.add_dependency(%q<ruby-opengl>, ["= 0.60.1"])
      s.add_dependency(%q<qtbindings>, ["= 4.6.3.4"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<gmath3D>, [">= 0"])
    s.add_dependency(%q<ruby-opengl>, ["= 0.60.1"])
    s.add_dependency(%q<qtbindings>, ["= 4.6.3.4"])
  end
end

