# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "disp3D"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Toshiyasu Shimizu"]
  s.date = "2011-12-11"
  s.description = "disp3D provide 3D GUI framework"
  s.email = "toshi0328@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "disp3D.gemspec",
    "example/stl_viewer/document.rb",
    "example/stl_viewer/document_ctrl.rb",
    "example/stl_viewer/main.rb",
    "example/stl_viewer/qt_widget_controller.rb",
    "example/stl_viewer/stl_viewer.rb",
    "example/tutorial/01_helloworld.rb",
    "example/tutorial/02_elements.rb",
    "example/tutorial/03_CameraScene.rb",
    "example/tutorial/04_Qt.rb",
    "example/tutorial/05_Pick.rb",
    "example/tutorial/06_FileParser.rb",
    "example/tutorial/07_SceneGraph.rb",
    "example/tutorial/08_SceneGraph2.rb",
    "example/tutorial/09_Texture.rb",
    "example/tutorial/10_Animation.rb",
    "example/tutorial/10_AnimationQt.rb",
    "example/tutorial/11_MultiView.rb",
    "example/tutorial/12_Light.rb",
    "example/tutorial/13_RectPick.rb",
    "example/tutorial/14_LineRubberband.rb",
    "example/tutorial/data/bunny.stl",
    "example/tutorial/data/test.png",
    "example/tutorial/data/test2.jpg",
    "lib/camera.rb",
    "lib/compass.rb",
    "lib/disp3D.rb",
    "lib/disp3D_ext.rb",
    "lib/exception.rb",
    "lib/gl_view.rb",
    "lib/glut_window.rb",
    "lib/light.rb",
    "lib/manipulator.rb",
    "lib/node/node.rb",
    "lib/node/node_arrows.rb",
    "lib/node/node_collection.rb",
    "lib/node/node_cone.rb",
    "lib/node/node_coord.rb",
    "lib/node/node_leaf.rb",
    "lib/node/node_lines.rb",
    "lib/node/node_points.rb",
    "lib/node/node_polylines.rb",
    "lib/node/node_rectangle.rb",
    "lib/node/node_sphere.rb",
    "lib/node/node_tea_pod.rb",
    "lib/node/node_text.rb",
    "lib/node/node_tris.rb",
    "lib/node/node_workplane.rb",
    "lib/path_info.rb",
    "lib/picked_result.rb",
    "lib/picker.rb",
    "lib/qt_widget_gl.rb",
    "lib/scene_graph.rb",
    "lib/stl.rb",
    "test/data/cube-ascii.stl",
    "test/data/cube-binary.stl",
    "test/helper.rb",
    "test/node/test_node.rb",
    "test/node/test_node_arrows.rb",
    "test/node/test_node_collection.rb",
    "test/node/test_node_leaf.rb",
    "test/node/test_node_lines.rb",
    "test/node/test_node_points.rb",
    "test/node/test_node_polylines.rb",
    "test/node/test_node_rectangle.rb",
    "test/node/test_node_text.rb",
    "test/node/test_node_tris.rb",
    "test/node/test_node_workplane.rb",
    "test/test_camera.rb",
    "test/test_gl_view.rb",
    "test/test_manipulator.rb",
    "test/test_path_info.rb",
    "test/test_picked_result.rb",
    "test/test_picker.rb",
    "test/test_scene_graph.rb",
    "test/test_stl.rb"
  ]
  s.homepage = "http://github.com/toshi0328/disp3D"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "disp3D provide 3D GUI framework."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<gmath3D>, ["~> 1.0.0"])
      s.add_development_dependency(%q<ruby-opengl>, ["= 0.60.1"])
      s.add_development_dependency(%q<rmagick>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<gmath3D>, ["~> 1.0.0"])
      s.add_dependency(%q<ruby-opengl>, ["= 0.60.1"])
      s.add_dependency(%q<rmagick>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<gmath3D>, ["~> 1.0.0"])
    s.add_dependency(%q<ruby-opengl>, ["= 0.60.1"])
    s.add_dependency(%q<rmagick>, [">= 0"])
  end
end

