# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{disp3D}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Toshiyasu Shimizu"]
  s.date = %q{2011-11-03}
  s.description = %q{disp3D provide 3D GUI framework}
  s.email = %q{toshi0328@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "disp3D.gemspec",
    "example/stl_viewer/app_model.rb",
    "example/stl_viewer/document.rb",
    "example/stl_viewer/document_ctrl.rb",
    "example/stl_viewer/gl_ctrl.rb",
    "example/stl_viewer/main.rb",
    "example/stl_viewer/mesh_info.rb",
    "example/stl_viewer/stl_viewer.rb",
    "lib/camera.rb",
    "lib/disp3D.rb",
    "lib/dsl.rb",
    "lib/gl_view.rb",
    "lib/glut_window.rb",
    "lib/light.rb",
    "lib/manipulator.rb",
    "lib/node.rb",
    "lib/node_arrows.rb",
    "lib/node_collection.rb",
    "lib/node_leaf.rb",
    "lib/node_lines.rb",
    "lib/node_points.rb",
    "lib/node_polylines.rb",
    "lib/node_tea_pod.rb",
    "lib/node_text.rb",
    "lib/node_tris.rb",
    "lib/picked_result.rb",
    "lib/picker.rb",
    "lib/qt_widget_gl.rb",
    "lib/scene_graph.rb",
    "lib/stl.rb",
    "lib/util.rb",
    "test/helper.rb",
    "test/test_data/binary_test.stl",
    "test/test_data/cube-ascii.stl",
    "test/test_dsl.rb",
    "test/test_glut_window.rb",
    "test/test_qtgl.rb",
    "test/test_stl.rb",
    "test/test_tea_pod.rb"
  ]
  s.homepage = %q{http://github.com/toshi0328/disp3D}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{disp3D provide 3D GUI framework.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<gmath3D>, [">= 0"])
      s.add_development_dependency(%q<ruby-opengl>, ["= 0.60.1"])
      s.add_development_dependency(%q<qtbindings>, ["= 4.6.3.4"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<gmath3D>, [">= 0"])
      s.add_dependency(%q<ruby-opengl>, ["= 0.60.1"])
      s.add_dependency(%q<qtbindings>, ["= 4.6.3.4"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<gmath3D>, [">= 0"])
    s.add_dependency(%q<ruby-opengl>, ["= 0.60.1"])
    s.add_dependency(%q<qtbindings>, ["= 4.6.3.4"])
  end
end

